name: SkyWarsTeam
main: KaitoDoDo\SkyWarsTeam\SkyWarsTeam
author: OlimpoCraft
version: 1.1
api: [3.8.2]

commands:
    stm:
        usage: /stm <leave-make>
        description: SkyWars-Commands
    lang:
        usage: /lang <en>
        description: SkyWars-English-Lang
    rankstm:
        usage: /rankstm
        description: SkyRank-Commands
    stmstart:
        usage: /stmstart
        description: SkyWars-Force start